/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GraphImport } from './routes/graph'
import { Route as CodebasesImport } from './routes/codebases'
import { Route as SearchImport } from './routes/search'
import { Route as SettingsImport } from './routes/settings'
import { Route as EditImport } from './routes/edit/$codebaseId/$path'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GraphRoute = GraphImport.update({
  path: '/graph',
  getParentRoute: () => rootRoute,
} as any)

const CodebasesRoute = CodebasesImport.update({
  path: '/codebases',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const EditRoute = EditImport.update({
  path: '/edit/$codebaseId/$path',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/codebases': {
      id: '/codebases'
      path: '/codebases'
      fullPath: '/codebases'
      preLoaderRoute: typeof CodebasesImport
      parentRoute: typeof rootRoute
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/edit/$codebaseId/$path': {
      id: '/edit/$codebaseId/$path'
      path: '/edit/$codebaseId/$path'
      fullPath: '/edit/$codebaseId/$path'
      preLoaderRoute: typeof EditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CodebasesRoute,
  GraphRoute,
  SearchRoute,
  SettingsRoute,
  EditRoute,
})

/* prettier-ignore-end */
