//! Content pruning, indexing admission gating, and work hoisting.

use super::*;

/// Decision returned by the content pruner for each node.
///
/// This enum is externally observable in tests so that pruning behavior
/// remains transparent and reversible at the contract surface.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PruningDecision {
    /// Node is kept for full indexing.
    Keep,
    /// Node is pruned because it appears to be generated code.
    GeneratedCode(String),
    /// Node is pruned because it has very low information content.
    LowInformation(String),
}

/// Selective content pruner for A+ memory discipline.
///
/// Identifies low-information nodes and recognized generated-code patterns
/// so they can be excluded from heavyweight indexing/search execution paths.
/// The pruner is conservative: user-authored high-signal files remain eligible.
///
/// Pruning is externally observable through the `PruningDecision` return value
/// and is reversible — the decision can be overridden by the caller.
#[derive(Debug, Clone)]
pub struct ContentPruner {
    /// Recognized generated-code file name suffixes.
    generated_suffixes: Vec<String>,
    /// Recognized generated-code path substrings.
    generated_path_patterns: Vec<String>,
    /// Minimum content length (bytes) below which a node is considered
    /// low-information. Nodes with content shorter than this are candidates
    /// for pruning unless they have a non-trivial symbol name.
    min_content_bytes: usize,
}

impl Default for ContentPruner {
    fn default() -> Self {
        Self::new()
    }
}

impl ContentPruner {
    /// Create a new pruner with default generated-code patterns.
    pub fn new() -> Self {
        Self {
            generated_suffixes: vec![
                ".min.js".into(),
                ".min.css".into(),
                ".pb.go".into(),
                ".generated.rs".into(),
                ".bundle.js".into(),
                ".chunk.js".into(),
                "_pb2.py".into(),
                ".d.ts".into(),
            ],
            generated_path_patterns: vec![
                "node_modules".into(),
                "/vendor/".into(),
                "/generated/".into(),
                "/autogenerated/".into(),
                "\\vendor\\".into(),
            ],
            min_content_bytes: 16,
        }
    }

    /// Evaluate whether a node should be pruned from heavyweight paths.
    ///
    /// Returns a `PruningDecision` explaining the outcome. The caller can
    /// inspect the decision and choose to override it.
    pub fn evaluate(&self, file_path: &str, content: &str, symbol_name: &str) -> PruningDecision {
        // Check generated-code file patterns first (highest confidence).
        let fp_lower = file_path.to_ascii_lowercase();
        for suffix in &self.generated_suffixes {
            if fp_lower.ends_with(suffix) {
                return PruningDecision::GeneratedCode(format!(
                    "file ends with generated suffix '{}'",
                    suffix
                ));
            }
        }
        for pattern in &self.generated_path_patterns {
            if fp_lower.contains(pattern) {
                return PruningDecision::GeneratedCode(format!(
                    "file path contains generated pattern '{}'",
                    pattern
                ));
            }
        }

        // Check low-information content. Very short content with a trivial
        // symbol name is unlikely to carry meaningful search signal.
        if content.len() < self.min_content_bytes && symbol_name.len() < 3 {
            return PruningDecision::LowInformation(format!(
                "content {} bytes < min {}, symbol '{}' < 3 chars",
                content.len(),
                self.min_content_bytes,
                symbol_name
            ));
        }

        PruningDecision::Keep
    }

    /// Check if a file path matches generated-code patterns without
    /// considering content. Useful for pre-filtering during file scanning.
    pub fn is_generated_path(&self, file_path: &str) -> bool {
        let fp_lower = file_path.to_ascii_lowercase();
        for suffix in &self.generated_suffixes {
            if fp_lower.ends_with(suffix) {
                return true;
            }
        }
        for pattern in &self.generated_path_patterns {
            if fp_lower.contains(pattern) {
                return true;
            }
        }
        false
    }
}

/// Bound-gated indexing admission control.
///
/// When indexing pressure exceeds configured conservative bounds, the gate
/// sheds, defers, or otherwise gates additional parse/index work instead of
/// admitting unbounded resident state growth.
///
/// The gate tracks cumulative node count and content bytes within a single
/// indexing batch. When either cap is exceeded, subsequent nodes are shed
/// (skipped) rather than admitted.
#[derive(Debug)]
pub struct IndexingAdmissionGate {
    /// Maximum nodes to admit in this batch.
    node_cap: usize,
    /// Maximum total content bytes to admit in this batch.
    byte_cap: usize,
    /// Nodes admitted so far.
    nodes_admitted: usize,
    /// Content bytes admitted so far.
    bytes_admitted: usize,
    /// Nodes shed (rejected) so far.
    nodes_shed: usize,
}

impl IndexingAdmissionGate {
    /// Create a new gate with default A+ caps.
    pub fn new() -> Self {
        Self {
            node_cap: INDEXING_BATCH_NODE_CAP,
            byte_cap: INDEXING_BATCH_BYTE_CAP,
            nodes_admitted: 0,
            bytes_admitted: 0,
            nodes_shed: 0,
        }
    }

    /// Create a gate with custom caps (for testing).
    pub fn with_caps(node_cap: usize, byte_cap: usize) -> Self {
        Self {
            node_cap,
            byte_cap,
            nodes_admitted: 0,
            bytes_admitted: 0,
            nodes_shed: 0,
        }
    }

    /// Try to admit a node. Returns `true` if the node is admitted, `false`
    /// if it is shed due to exceeding bounds.
    pub fn try_admit(&mut self, content_bytes: usize) -> bool {
        if self.nodes_admitted >= self.node_cap {
            self.nodes_shed += 1;
            return false;
        }
        if self.bytes_admitted + content_bytes > self.byte_cap {
            self.nodes_shed += 1;
            return false;
        }
        self.nodes_admitted += 1;
        self.bytes_admitted += content_bytes;
        true
    }

    /// Number of nodes admitted so far.
    pub fn nodes_admitted(&self) -> usize {
        self.nodes_admitted
    }

    /// Number of nodes shed (rejected) so far.
    pub fn nodes_shed(&self) -> usize {
        self.nodes_shed
    }

    /// Total content bytes admitted so far.
    pub fn bytes_admitted(&self) -> usize {
        self.bytes_admitted
    }

    /// Reset the gate for a new batch.
    pub fn reset(&mut self) {
        self.nodes_admitted = 0;
        self.bytes_admitted = 0;
        self.nodes_shed = 0;
    }
}

impl Default for IndexingAdmissionGate {
    fn default() -> Self {
        Self::new()
    }
}

/// Cached intermediate work entry for the work hoister.
struct HoistedWork {
    /// The TF-IDF embedding computed for this content.
    embedding: Vec<f32>,
    /// The neural embedding computed for this content (if available).
    /// Cached alongside TF-IDF to avoid redundant ONNX inference on cache hits.
    neural_embedding: Option<Vec<f32>>,
    /// Approximate byte size of this cache entry.
    byte_size: usize,
}

/// Bounded repeated-work hoister.
///
/// Caches intermediate TF-IDF and neural embedding results keyed by a BLAKE3
/// content hash within a bounded window. When the same content is encountered again
/// (e.g., during incremental reindexing of unchanged files), the hoisted
/// result is reused instead of recomputing the embedding.
///
/// The cache is bounded by both entry count and total bytes. When either
/// limit is exceeded, the least-recently-used entry is evicted.
pub struct WorkHoister {
    cache: LruCache<blake3::Hash, HoistedWork>,
    tracked_bytes: usize,
    max_bytes: usize,
}

impl WorkHoister {
    /// Create a new hoister with default A+ bounds.
    pub fn new() -> Self {
        Self {
            cache: LruCache::new(NonZeroUsize::new(WORK_HOISTER_MAX_ENTRIES).unwrap()),
            tracked_bytes: 0,
            max_bytes: WORK_HOISTER_MAX_BYTES,
        }
    }

    /// Create a hoister with custom bounds (for testing).
    pub fn with_bounds(max_entries: usize, max_bytes: usize) -> Self {
        Self {
            cache: LruCache::new(NonZeroUsize::new(max_entries.max(1)).unwrap()),
            tracked_bytes: 0,
            max_bytes,
        }
    }

    /// Look up a previously hoisted embedding for the given content.
    /// Returns `Some((tfidf_embedding, neural_embedding))` if found, `None` otherwise.
    pub fn lookup(&mut self, content: &str) -> Option<(Vec<f32>, Option<Vec<f32>>)> {
        let hash = blake3::hash(content.as_bytes());
        self.cache
            .get(&hash)
            .map(|entry| (entry.embedding.clone(), entry.neural_embedding.clone()))
    }

    /// Store a computed embedding for the given content.
    /// If the cache is full, evicts the least-recently-used entry first.
    pub fn store(
        &mut self,
        content: &str,
        embedding: Vec<f32>,
        neural_embedding: Option<Vec<f32>>,
    ) {
        let hash = blake3::hash(content.as_bytes());
        let neural_byte_size = neural_embedding
            .as_ref()
            .map_or(0, |v| v.len() * std::mem::size_of::<f32>());
        let byte_size = 32 + embedding.len() * std::mem::size_of::<f32>() + neural_byte_size;
        let entry = HoistedWork {
            embedding,
            neural_embedding,
            byte_size,
        };

        // `push` (not `put`) so the entry removed for a count-capacity eviction
        // is returned and its bytes subtracted. `put` silently drops that entry,
        // inflating tracked_bytes and causing over-eviction.
        if let Some((_, existing)) = self.cache.push(hash, entry) {
            self.tracked_bytes = self.tracked_bytes.saturating_sub(existing.byte_size);
        }

        // Evict until there is room.
        while self.tracked_bytes + byte_size > self.max_bytes && !self.cache.is_empty() {
            if let Some((evicted_hash, evicted)) = self.cache.pop_lru() {
                self.tracked_bytes = self.tracked_bytes.saturating_sub(evicted.byte_size);
                // If the just-inserted entry was evicted, stop — don't count it.
                if evicted_hash == hash {
                    return;
                }
            }
        }

        // Only increment tracked_bytes if the entry is still in the cache after eviction.
        if self.cache.contains(&hash) {
            self.tracked_bytes += byte_size;
        }
    }

    /// Number of entries currently in the hoister.
    pub fn len(&self) -> usize {
        self.cache.len()
    }

    /// Whether the hoister is empty.
    pub fn is_empty(&self) -> bool {
        self.cache.is_empty()
    }

    /// Tracked byte usage.
    pub fn bytes_used(&self) -> usize {
        self.tracked_bytes
    }

    /// Clear the hoister.
    pub fn clear(&mut self) {
        self.cache.clear();
        self.tracked_bytes = 0;
    }
}

impl Default for WorkHoister {
    fn default() -> Self {
        Self::new()
    }
}
